### ISSUE TITLE
RoundingMode missing

### ISSUE THREAD

**Issue by MrStahlfelge** [YuryMikhailuts/kig-decimal#1]
Hi, 

first of all, thanks for going the route by reusing the GWT lib. I always had good experiences with GWT's BigDecimal, while I experience bug after bug with the other Kotlin Multiplatform libs, so I think this is the right way to go.

For me two things are missing so far:

`fun String.toBigDecimal() = BigDecimal(this)`

(easy to add)

and

`fun setScale(newScale: Int, roundingMode: RoundingMode): BigDecimal`

I made an attempt to add myself, but I am getting stuck how to add RoundingMode as a type alias. When adding it as an own enum, the whole other type alias is not working any more. Unfortunately, my code depends on the Rounding Mode. My attempt to integrate the lib ended in "Rounding necessary" error (which is a good sign, as it is!)

Also, please translate the license and readme into English.

**Comment by YuryMikhailuts** [comment]
Good afternoon. Thank you for showing interest in this project. I'll start answering your questions with the last one:

- About the translation into English. This repository on GitHub is a mirror. The original is here 'https://gitflic.ru/project/mikhaylutsyury/kig-decimal ' and I work there entirely in Russian. If you want to help with the duplication of materials in English, please register at https://gitflic.ru and I will add you to the project team.

- About `RoundingMode`. I think that a solution using `external class` or `external interface` is best suited here. Since I did in `bigdecimal.MathContext` for JS.

- About `String.toBigDecimal()`. As soon as you make a merge request to the main repository on https://gitflic.ru I'll approve it right away.

**Comment by MrStahlfelge** [comment]
I made the necessary changes and will make a PR here. As I can't speak Russian I won't work on a site that I can't understand, but you can pull in my change anyway by setting my repo as a remote.

**Comment by MrStahlfelge** [comment]
Opened #3

**Comment by YuryMikhailuts** [comment]
> I made the necessary changes and will make a PR here. As I can't speak Russian I won't work on a site that I can't understand, but you can pull in my change anyway by setting my repo as a remote.

It looks like on gitflic.ru so far, it is not possible to work in English. In this case, I will accept your PR here on GitHub. But I have already sent a question about English language support to the service support service gitflic.ru .
